### ISSUE TITLE
Type Errors

### ISSUE THREAD

**Issue by FullPint** [daymos/simple_keras_GAN#2]
If you were to just run the code you have it will produce type error due to the division that is made throughout the code. The reason being -- you'll produce floats when they need to be ints. 

I can fix it if you like.

**Comment by nakarin** [comment]
@FullPint  Please fix its.

**Comment by FullPint** [comment]
@nakarin I made a pull request, it's up to @daymos  to accept it or not. 
The changes aren't anything difficult but if you can't wait, there is a fork in my profile with the changes necessary made.

**Comment by daymos** [comment]
good catch @FullPint, its merged. I'm closing this issue
